ifneq (,$(filter lifi,$(USEMODULE)))
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_gpio_irq
endif


#ifneq (,$(filter gnrc_ipv6,$(USEMODULE)))
#  USEMODULE += gnrc_sixlowpan
#endif

