FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq

ifneq (,$(filter lifi,$(USEMODULE)))
  USEMODULE += xtimer
endif


#ifneq (,$(filter gnrc_ipv6,$(USEMODULE)))
#  USEMODULE += gnrc_sixlowpan
#endif

